# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rastercalcdialogbase.ui'
#
# Created: Mon Jan 18 18:06:15 2010
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RasterCalcDialog(object):
    def setupUi(self, RasterCalcDialog):
        RasterCalcDialog.setObjectName("RasterCalcDialog")
        RasterCalcDialog.resize(741, 379)
        RasterCalcDialog.setSizeGripEnabled(False)
        self.verticalLayout_2 = QtGui.QVBoxLayout(RasterCalcDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rasterTree = QtGui.QTreeWidget(RasterCalcDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rasterTree.sizePolicy().hasHeightForWidth())
        self.rasterTree.setSizePolicy(sizePolicy)
        self.rasterTree.setMinimumSize(QtCore.QSize(180, 0))
        self.rasterTree.setObjectName("rasterTree")
        self.horizontalLayout_2.addWidget(self.rasterTree)
        self.bandList = QtGui.QListWidget(RasterCalcDialog)
        self.bandList.setObjectName("bandList")
        self.horizontalLayout_2.addWidget(self.bandList)
        self.frame = QtGui.QFrame(RasterCalcDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnRParen = QtGui.QPushButton(self.frame)
        self.btnRParen.setObjectName("btnRParen")
        self.verticalLayout_3.addWidget(self.btnRParen)
        self.btnLParen = QtGui.QPushButton(self.frame)
        self.btnLParen.setObjectName("btnLParen")
        self.verticalLayout_3.addWidget(self.btnLParen)
        self.btnBand = QtGui.QPushButton(self.frame)
        self.btnBand.setObjectName("btnBand")
        self.verticalLayout_3.addWidget(self.btnBand)
        self.btnClip = QtGui.QPushButton(self.frame)
        self.btnClip.setEnabled(False)
        self.btnClip.setObjectName("btnClip")
        self.verticalLayout_3.addWidget(self.btnClip)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cmbPresets = QtGui.QComboBox(self.frame)
        self.cmbPresets.setObjectName("cmbPresets")
        self.cmbPresets.addItem(QtCore.QString())
        self.cmbPresets.addItem(QtCore.QString())
        self.gridLayout_2.addWidget(self.cmbPresets, 0, 0, 1, 3)
        self.btnSin = QtGui.QPushButton(self.frame)
        self.btnSin.setEnabled(False)
        self.btnSin.setObjectName("btnSin")
        self.gridLayout_2.addWidget(self.btnSin, 1, 0, 1, 1)
        self.btnAsin = QtGui.QPushButton(self.frame)
        self.btnAsin.setEnabled(False)
        self.btnAsin.setObjectName("btnAsin")
        self.gridLayout_2.addWidget(self.btnAsin, 1, 1, 1, 1)
        self.btnExp = QtGui.QPushButton(self.frame)
        self.btnExp.setEnabled(False)
        self.btnExp.setObjectName("btnExp")
        self.gridLayout_2.addWidget(self.btnExp, 1, 2, 1, 1)
        self.btnCos = QtGui.QPushButton(self.frame)
        self.btnCos.setEnabled(False)
        self.btnCos.setObjectName("btnCos")
        self.gridLayout_2.addWidget(self.btnCos, 2, 0, 1, 1)
        self.btnAcos = QtGui.QPushButton(self.frame)
        self.btnAcos.setEnabled(False)
        self.btnAcos.setObjectName("btnAcos")
        self.gridLayout_2.addWidget(self.btnAcos, 2, 1, 1, 1)
        self.btnLog = QtGui.QPushButton(self.frame)
        self.btnLog.setEnabled(False)
        self.btnLog.setObjectName("btnLog")
        self.gridLayout_2.addWidget(self.btnLog, 2, 2, 1, 1)
        self.btnTan = QtGui.QPushButton(self.frame)
        self.btnTan.setEnabled(False)
        self.btnTan.setObjectName("btnTan")
        self.gridLayout_2.addWidget(self.btnTan, 3, 0, 1, 1)
        self.btnAtan = QtGui.QPushButton(self.frame)
        self.btnAtan.setEnabled(False)
        self.btnAtan.setObjectName("btnAtan")
        self.gridLayout_2.addWidget(self.btnAtan, 3, 1, 1, 1)
        self.btnPower = QtGui.QPushButton(self.frame)
        self.btnPower.setObjectName("btnPower")
        self.gridLayout_2.addWidget(self.btnPower, 3, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 4, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnMul = QtGui.QPushButton(self.frame)
        self.btnMul.setObjectName("btnMul")
        self.verticalLayout.addWidget(self.btnMul)
        self.btnDiv = QtGui.QPushButton(self.frame)
        self.btnDiv.setObjectName("btnDiv")
        self.verticalLayout.addWidget(self.btnDiv)
        self.btnSub = QtGui.QPushButton(self.frame)
        self.btnSub.setObjectName("btnSub")
        self.verticalLayout.addWidget(self.btnSub)
        self.btnAdd = QtGui.QPushButton(self.frame)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.commandTextEdit = QtGui.QTextEdit(RasterCalcDialog)
        self.commandTextEdit.setObjectName("commandTextEdit")
        self.horizontalLayout_3.addWidget(self.commandTextEdit)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnClearCommand = QtGui.QPushButton(RasterCalcDialog)
        self.btnClearCommand.setObjectName("btnClearCommand")
        self.verticalLayout_4.addWidget(self.btnClearCommand)
        self.btnSaveExpression = QtGui.QPushButton(RasterCalcDialog)
        self.btnSaveExpression.setEnabled(False)
        self.btnSaveExpression.setObjectName("btnSaveExpression")
        self.verticalLayout_4.addWidget(self.btnSaveExpression)
        self.btnLoadExpression = QtGui.QPushButton(RasterCalcDialog)
        self.btnLoadExpression.setObjectName("btnLoadExpression")
        self.verticalLayout_4.addWidget(self.btnLoadExpression)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(RasterCalcDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cmbPixelFormat = QtGui.QComboBox(RasterCalcDialog)
        self.cmbPixelFormat.setObjectName("cmbPixelFormat")
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.cmbPixelFormat.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.cmbPixelFormat)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(RasterCalcDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.leFileName = QtGui.QLineEdit(RasterCalcDialog)
        self.leFileName.setObjectName("leFileName")
        self.horizontalLayout.addWidget(self.leFileName)
        self.btnBrowse = QtGui.QPushButton(RasterCalcDialog)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.loadCheckBox = QtGui.QCheckBox(RasterCalcDialog)
        self.loadCheckBox.setObjectName("loadCheckBox")
        self.verticalLayout_2.addWidget(self.loadCheckBox)
        self.buttonBox = QtGui.QDialogButtonBox(RasterCalcDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(RasterCalcDialog)
        self.bandList.setCurrentRow(-1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), RasterCalcDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), RasterCalcDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RasterCalcDialog)

    def retranslateUi(self, RasterCalcDialog):
        RasterCalcDialog.setWindowTitle(QtGui.QApplication.translate("RasterCalcDialog", "RasterCalc", None, QtGui.QApplication.UnicodeUTF8))
        self.rasterTree.headerItem().setText(0, QtGui.QApplication.translate("RasterCalcDialog", "Available rasters", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRParen.setText(QtGui.QApplication.translate("RasterCalcDialog", "(", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLParen.setText(QtGui.QApplication.translate("RasterCalcDialog", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBand.setWhatsThis(QtGui.QApplication.translate("RasterCalcDialog", "Get band from raster", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBand.setText(QtGui.QApplication.translate("RasterCalcDialog", "@", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClip.setWhatsThis(QtGui.QApplication.translate("RasterCalcDialog", "Clip lower and upper values", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClip.setText(QtGui.QApplication.translate("RasterCalcDialog", "clip", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPresets.setItemText(0, QtGui.QApplication.translate("RasterCalcDialog", "NDVI (TM/ETM+)", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPresets.setItemText(1, QtGui.QApplication.translate("RasterCalcDialog", "Difference", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSin.setText(QtGui.QApplication.translate("RasterCalcDialog", "sin", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAsin.setText(QtGui.QApplication.translate("RasterCalcDialog", "asin", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExp.setText(QtGui.QApplication.translate("RasterCalcDialog", "exp", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCos.setText(QtGui.QApplication.translate("RasterCalcDialog", "cos", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAcos.setText(QtGui.QApplication.translate("RasterCalcDialog", "acos", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLog.setText(QtGui.QApplication.translate("RasterCalcDialog", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTan.setText(QtGui.QApplication.translate("RasterCalcDialog", "tan", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAtan.setText(QtGui.QApplication.translate("RasterCalcDialog", "atan", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPower.setWhatsThis(QtGui.QApplication.translate("RasterCalcDialog", "Raise to power", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPower.setText(QtGui.QApplication.translate("RasterCalcDialog", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMul.setWhatsThis(QtGui.QApplication.translate("RasterCalcDialog", "Multiply arguments", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMul.setText(QtGui.QApplication.translate("RasterCalcDialog", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDiv.setWhatsThis(QtGui.QApplication.translate("RasterCalcDialog", "Divide arguments", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDiv.setText(QtGui.QApplication.translate("RasterCalcDialog", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSub.setWhatsThis(QtGui.QApplication.translate("RasterCalcDialog", "Subtract argiments", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSub.setText(QtGui.QApplication.translate("RasterCalcDialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setWhatsThis(QtGui.QApplication.translate("RasterCalcDialog", "Add arguments", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("RasterCalcDialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClearCommand.setText(QtGui.QApplication.translate("RasterCalcDialog", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveExpression.setText(QtGui.QApplication.translate("RasterCalcDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadExpression.setText(QtGui.QApplication.translate("RasterCalcDialog", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RasterCalcDialog", "Pixel format", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(0, QtGui.QApplication.translate("RasterCalcDialog", "Byte", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(1, QtGui.QApplication.translate("RasterCalcDialog", "UInt16", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(2, QtGui.QApplication.translate("RasterCalcDialog", "Int16", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(3, QtGui.QApplication.translate("RasterCalcDialog", "UInt32", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(4, QtGui.QApplication.translate("RasterCalcDialog", "Int32", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(5, QtGui.QApplication.translate("RasterCalcDialog", "Float32", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(6, QtGui.QApplication.translate("RasterCalcDialog", "Float64", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(7, QtGui.QApplication.translate("RasterCalcDialog", "CInt16", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(8, QtGui.QApplication.translate("RasterCalcDialog", "CInt32", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(9, QtGui.QApplication.translate("RasterCalcDialog", "CFloat32", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPixelFormat.setItemText(10, QtGui.QApplication.translate("RasterCalcDialog", "CFloat64", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RasterCalcDialog", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setText(QtGui.QApplication.translate("RasterCalcDialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.loadCheckBox.setText(QtGui.QApplication.translate("RasterCalcDialog", "Add result to the map canvas", None, QtGui.QApplication.UnicodeUTF8))

